const fs = require('fs');
const path = require('path');

const locales_dir = path.join(__dirname, 'src/locales');

const translations = {
    'en': {
        'landing.desc': 'Browse, filter and download student projects without logging in.',
        'guest.hero_subtitle': 'Browse, filter and download student projects without logging in.',
        'project_types.webgl': 'WebGL Game',
        'project.webgl_section': 'WebGL Game',
        'project.webgl_play': 'Play in browser',
        'project.webgl_open': 'Open in new tab',
        'add_project.add_subtitle': 'Fill in your project details and publish it to the portal.',
        'add_project.edit_subtitle': 'Update your project information.',
        'add_project.basic_section': 'Basic information',
        'add_project.media_section': 'Media',
        'add_project.required_note': 'Fields marked with * are required.',
        'add_project.webgl_source_label': 'How to display the game',
        'add_project.webgl_mode_build': 'Upload build',
        'add_project.webgl_mode_url': 'External URL',
        'add_project.webgl_build_label': 'WebGL build (ZIP archive)',
        'add_project.webgl_build_btn': 'Choose file',
        'add_project.webgl_build_hint': 'Upload a ZIP archive containing your exported WebGL build from Unity or another tool. The archive must include an index.html file. Max size: 100 MB.',
        'add_project.webgl_url_label': 'WebGL game URL',
        'add_project.webgl_url_hint': 'The URL where the game is hosted (e.g. itch.io, GitHub Pages, your own server). The game will be embedded directly on the portal.',
        'add_project.missing_desc_title': 'Description too short',
        'add_project.missing_desc_desc': 'Description must contain at least 10 words.',
        'add_project.missing_splash_title': 'Missing project thumbnail',
        'add_project.missing_splash_desc': 'Upload a poster/thumbnail image for the project. It is displayed on the project card.'
    },
    'sk': {
        'landing.desc': 'Prezerajte, filtrujte a sťahujte študentské projekty bez prihlásenia.',
        'guest.hero_subtitle': 'Prezerajte, filtrujte a sťahujte študentské projekty bez prihlásenia.',
    },
    'cs': {
        'landing.desc': 'Prohlížejte, filtrujte a stahujte studentské projekty bez přihlášení.',
        'guest.hero_subtitle': 'Prohlížejte, filtrujte a stahujte studentské projekty bez přihlášení.',
        'project_types.webgl': 'WebGL Hra',
        'project.webgl_section': 'WebGL Hra',
        'project.webgl_play': 'Hrát v prohlížeči',
        'project.webgl_open': 'Otevřít novém okně',
        'add_project.add_subtitle': 'Vyplňte detaily a publikujte svůj projekt na portálu.',
        'add_project.edit_subtitle': 'Aktualizujte informace o projektu.',
        'add_project.basic_section': 'Základní informace',
        'add_project.media_section': 'Média',
        'add_project.required_note': 'Pole označená * jsou povinná.',
        'add_project.webgl_source_label': 'Jak hru zobrazit',
        'add_project.webgl_mode_build': 'Nahrát build',
        'add_project.webgl_mode_url': 'Externí URL',
        'add_project.webgl_build_label': 'WebGL build (ZIP archiv)',
        'add_project.webgl_build_btn': 'Vybrat soubor',
        'add_project.webgl_build_hint': 'Nahrajte ZIP archiv s exportovaným WebGL buildem. Archiv musí obsahovat index.html. Max velikost: 100 MB.',
        'add_project.webgl_url_label': 'URL adresa WebGL hry',
        'add_project.webgl_url_hint': 'Adresa, kde je hra hostována. Bude vložena přímo do portálu.',
        'add_project.missing_desc_title': 'Popis je příliš krátký',
        'add_project.missing_desc_desc': 'Popis musí obsahovat alespoň 10 slov.',
        'add_project.missing_splash_title': 'Chybí náhled projektu',
        'add_project.missing_splash_desc': 'Nahrajte plakát (thumbnail) pro projekt. Bude zobrazen na kartě projektu.'
    },
    'de': {
        'landing.desc': 'Studentenprojekte ohne Anmeldung durchsuchen, filtern und herunterladen.',
        'guest.hero_subtitle': 'Studentenprojekte ohne Anmeldung durchsuchen, filtern und herunterladen.',
        'project_types.webgl': 'WebGL-Spiel',
        'project.webgl_section': 'WebGL-Spiel',
        'project.webgl_play': 'Im Browser spielen',
        'project.webgl_open': 'In neuem Tab öffnen',
        'add_project.add_subtitle': 'Füllen Sie die Projektdetails aus und veröffentlichen Sie sie auf dem Portal.',
        'add_project.edit_subtitle': 'Aktualisieren Sie Ihre Projektinformationen.',
        'add_project.basic_section': 'Grundlegende Informationen',
        'add_project.media_section': 'Medien',
        'add_project.required_note': 'Mit * markierte Felder sind Pflichtfelder.',
        'add_project.webgl_source_label': 'So wird das Spiel angezeigt',
        'add_project.webgl_mode_build': 'Build hochladen',
        'add_project.webgl_mode_url': 'Externe URL',
        'add_project.webgl_build_label': 'WebGL-Build (ZIP-Archiv)',
        'add_project.webgl_build_btn': 'Datei auswählen',
        'add_project.webgl_build_hint': 'Laden Sie ein ZIP-Archiv mit Ihrem WebGL-Build hoch. Das Archiv muss eine index.html-Datei enthalten. Max. Größe: 100 MB.',
        'add_project.webgl_url_label': 'WebGL-Spiel-URL',
        'add_project.webgl_url_hint': 'Die URL, unter der das Spiel gehostet wird. Das Spiel wird direkt in das Portal eingebettet.',
        'add_project.missing_desc_title': 'Beschreibung zu kurz',
        'add_project.missing_desc_desc': 'Die Beschreibung muss mindestens 10 Wörter enthalten.',
        'add_project.missing_splash_title': 'Projekt-Miniaturbild fehlt',
        'add_project.missing_splash_desc': 'Laden Sie ein Poster/Miniaturbild für das Projekt hoch. Es wird auf der Projektkarte angezeigt.'
    },
    'es': {
        'landing.desc': 'Explora, filtra y descarga proyectos de estudiantes sin iniciar sesión.',
        'guest.hero_subtitle': 'Explora, filtra y descarga proyectos de estudiantes sin iniciar sesión.',
        'project_types.webgl': 'Juego WebGL',
        'project.webgl_section': 'Juego WebGL',
        'project.webgl_play': 'Jugar en el navegador',
        'project.webgl_open': 'Abrir en una pestaña nueva',
        'add_project.add_subtitle': 'Completa los detalles de tu proyecto y publícalo en el portal.',
        'add_project.edit_subtitle': 'Actualiza la información de tu proyecto.',
        'add_project.basic_section': 'Información básica',
        'add_project.media_section': 'Multimedia',
        'add_project.required_note': 'Los campos marcados con * son obligatorios.',
        'add_project.webgl_source_label': 'Cómo mostrar el juego',
        'add_project.webgl_mode_build': 'Subir compilación',
        'add_project.webgl_mode_url': 'URL externa',
        'add_project.webgl_build_label': 'Compilación WebGL (archivo ZIP)',
        'add_project.webgl_build_btn': 'Elegir archivo',
        'add_project.webgl_build_hint': 'Sube un archivo ZIP con tu compilación WebGL exportada. El archivo debe incluir un archivo index.html. Tamaño máx.: 100 MB.',
        'add_project.webgl_url_label': 'URL del juego WebGL',
        'add_project.webgl_url_hint': 'La URL donde está alojado el juego. El juego se incrustará directamente en el portal.',
        'add_project.missing_desc_title': 'Descripción demasiado corta',
        'add_project.missing_desc_desc': 'La descripción debe contener al menos 10 palabras.',
        'add_project.missing_splash_title': 'Falta la miniatura del proyecto',
        'add_project.missing_splash_desc': 'Sube un póster/miniatura para el proyecto. Se muestra en la tarjeta del proyecto.'
    },
    'fr': {
        'landing.desc': 'Parcourez, filtrez et téléchargez des projets sans vous connecter.',
        'guest.hero_subtitle': 'Parcourez, filtrez et téléchargez des projets sans vous connecter.',
        'project_types.webgl': 'Jeu WebGL',
        'project.webgl_section': 'Jeu WebGL',
        'project.webgl_play': 'Jouer dans le navigateur',
        'project.webgl_open': 'Ouvrir dans un nouvel onglet',
        'add_project.add_subtitle': 'Remplissez les détails et publiez-le sur le portail.',
        'add_project.edit_subtitle': 'Mettez à jour les informations du projet.',
        'add_project.basic_section': 'Informations de base',
        'add_project.media_section': 'Médias',
        'add_project.required_note': 'Les champs marqués d`un * sont obligatoires.',
        'add_project.webgl_source_label': 'Comment afficher le jeu',
        'add_project.webgl_mode_build': 'Uploader le build',
        'add_project.webgl_mode_url': 'URL externe',
        'add_project.webgl_build_label': 'Build WebGL (archive ZIP)',
        'add_project.webgl_build_btn': 'Choisir un fichier',
        'add_project.webgl_build_hint': 'Archive ZIP contenant index.html. Taille max : 100 Mo.',
        'add_project.webgl_url_label': 'URL du jeu WebGL',
        'add_project.webgl_url_hint': 'L URL où le jeu est hébergé. Le jeu sera intégré directement.',
        'add_project.missing_desc_title': 'Description trop courte',
        'add_project.missing_desc_desc': 'La description doit contenir au moins 10 mots.',
        'add_project.missing_splash_title': 'Miniature manquante',
        'add_project.missing_splash_desc': 'Téléchargez une affiche / miniature affichée sur la carte.'
    },
    'hu': {
        'landing.desc': 'Diákprojektek böngészése, szűrése és letöltése bejelentkezés nélkül.',
        'guest.hero_subtitle': 'Diákprojektek böngészése, szűrése és letöltése bejelentkezés nélkül.',
        'project_types.webgl': 'WebGL Játék',
        'project.webgl_section': 'WebGL Játék',
        'project.webgl_play': 'Játék a böngészőben',
        'project.webgl_open': 'Megnyitás új lapon',
        'add_project.add_subtitle': 'Töltse ki a projekt részleteit, és tegye közzé a portálon.',
        'add_project.edit_subtitle': 'Frissítse a projekt információit.',
        'add_project.basic_section': 'Alapinformációk',
        'add_project.media_section': 'Média',
        'add_project.required_note': 'A *-gal jelölt mezők kitöltése kötelező.',
        'add_project.webgl_source_label': 'Hogyan jelenjen meg a játék',
        'add_project.webgl_mode_build': 'Build feltöltése',
        'add_project.webgl_mode_url': 'Külső URL',
        'add_project.webgl_build_label': 'WebGL build (ZIP archívum)',
        'add_project.webgl_build_btn': 'Fájl kiválasztása',
        'add_project.webgl_build_hint': 'Töltsön fel egy ZIP archívumot. Az archívumnak tartalmaznia kell egy index.html fájlt. Max méret: 100 MB.',
        'add_project.webgl_url_label': 'WebGL játék URL',
        'add_project.webgl_url_hint': 'Az URL, ahol a játék található. A játék közvetlenül a portálba lesz ágyazva.',
        'add_project.missing_desc_title': 'A leírás túl rövid',
        'add_project.missing_desc_desc': 'A leírásnak legalább 10 szót kell tartalmaznia.',
        'add_project.missing_splash_title': 'Hiányzó projekt bélyegkép',
        'add_project.missing_splash_desc': 'Töltsön fel egy posztert/miniatűrt a projekthez.'
    },
    'it': {
        'landing.desc': 'Sfoglia, filtra e scarica i progetti degli studenti senza effettuare l`accesso.',
        'guest.hero_subtitle': 'Sfoglia, filtra e scarica i progetti degli studenti senza effettuare l`accesso.',
        'project_types.webgl': 'Gioco WebGL',
        'project.webgl_section': 'Gioco WebGL',
        'project.webgl_play': 'Gioca nel browser',
        'project.webgl_open': 'Apri in una nuova scheda',
        'add_project.add_subtitle': 'Compila i dettagli e pubblica il tuo progetto sul portale.',
        'add_project.edit_subtitle': 'Aggiorna le informazioni del tuo progetto.',
        'add_project.basic_section': 'Informazioni di base',
        'add_project.media_section': 'Media',
        'add_project.required_note': 'I campi contrassegnati con * sono obbligatori.',
        'add_project.webgl_source_label': 'Come visualizzare il gioco',
        'add_project.webgl_mode_build': 'Carica la build',
        'add_project.webgl_mode_url': 'URL esterno',
        'add_project.webgl_build_label': 'Build WebGL (archivio ZIP)',
        'add_project.webgl_build_btn': 'Scegli file',
        'add_project.webgl_build_hint': 'Carica un archivio ZIP contenente index.html. Dimensioni massime: 100 MB.',
        'add_project.webgl_url_label': 'URL del gioco WebGL',
        'add_project.webgl_url_hint': 'L`URL in cui è ospitato il gioco. Sarà incorporato nel portale.',
        'add_project.missing_desc_title': 'Descrizione troppo breve',
        'add_project.missing_desc_desc': 'La descrizione deve contenere almeno 10 parole.',
        'add_project.missing_splash_title': 'Miniatura del progetto mancante',
        'add_project.missing_splash_desc': 'Carica un poster/miniatura per il progetto.'
    },
    'nl': {
        'landing.desc': 'Blader, filter en download studentenprojecten zonder in te loggen.',
        'guest.hero_subtitle': 'Blader, filter en download studentenprojecten zonder in te loggen.',
        'project_types.webgl': 'WebGL Spel',
        'project.webgl_section': 'WebGL Spel',
        'project.webgl_play': 'Speel in browser',
        'project.webgl_open': 'Open in nieuw tabblad',
        'add_project.add_subtitle': 'Vul je projectdetails in en publiceer het op de portal.',
        'add_project.edit_subtitle': 'Update je projectinformatie.',
        'add_project.basic_section': 'Basisinformatie',
        'add_project.media_section': 'Media',
        'add_project.required_note': 'Gemarkeerde velden * zijn verplicht.',
        'add_project.webgl_source_label': 'Hoe het spel weer te geven',
        'add_project.webgl_mode_build': 'Upload build',
        'add_project.webgl_mode_url': 'Externe URL',
        'add_project.webgl_build_label': 'WebGL build (ZIP archief)',
        'add_project.webgl_build_btn': 'Kies bestand',
        'add_project.webgl_build_hint': 'Upload een ZIP archief met je WebGL build. Moet index.html bevatten. Max grootte: 100 MB.',
        'add_project.webgl_url_label': 'WebGL spel URL',
        'add_project.webgl_url_hint': 'De URL waar het spel is gehost. Het spel wordt direct op de portal ingesloten.',
        'add_project.missing_desc_title': 'Beschrijving te kort',
        'add_project.missing_desc_desc': 'Beschrijving moet minstens 10 woorden bevatten.',
        'add_project.missing_splash_title': 'Ontbrekende project thumbnail',
        'add_project.missing_splash_desc': 'Upload een poster/thumbnail afbeelding voor het project.'
    },
    'pl': {
        'landing.desc': 'Przeglądaj, filtruj i pobieraj projekty studentów bez logowania.',
        'guest.hero_subtitle': 'Przeglądaj, filtruj i pobieraj projekty studentów bez logowania.',
        'project_types.webgl': 'Gra WebGL',
        'project.webgl_section': 'Gra WebGL',
        'project.webgl_play': 'Graj w przeglądarce',
        'project.webgl_open': 'Otwórz w nowej karcie',
        'add_project.add_subtitle': 'Wypełnij szczegóły i opublikuj swój projekt na portalu.',
        'add_project.edit_subtitle': 'Zaktualizuj informacje o projekcie.',
        'add_project.basic_section': 'Podstawowe informacje',
        'add_project.media_section': 'Media',
        'add_project.required_note': 'Pola oznaczone * są wymagane.',
        'add_project.webgl_source_label': 'Jak wyświetlić grę',
        'add_project.webgl_mode_build': 'Wgraj build',
        'add_project.webgl_mode_url': 'Zewnętrzny adres URL',
        'add_project.webgl_build_label': 'Build WebGL (archiwum ZIP)',
        'add_project.webgl_build_btn': 'Wybierz plik',
        'add_project.webgl_build_hint': 'Prześlij archiwum ZIP zawierające wyeksportowany build WebGL. Archiwum musi zawierać plik index.html. Maks. rozmiar: 100 MB.',
        'add_project.webgl_url_label': 'Adres URL gry WebGL',
        'add_project.webgl_url_hint': 'Adres URL pod którym hostowana jest gra. Zostanie umieszczona bezpośrednio na portalu.',
        'add_project.missing_desc_title': 'Opis jest zbyt krótki',
        'add_project.missing_desc_desc': 'Opis musi zawierać co najmniej 10 słów.',
        'add_project.missing_splash_title': 'Brakująca miniatura projektu',
        'add_project.missing_splash_desc': 'Prześlij plakat/miniaturę dla projektu. Wyświetla się na karcie projektu.'
    },
    'pt': {
        'landing.desc': 'Navegue, filtre e baixe projetos de estudantes sem fazer login.',
        'guest.hero_subtitle': 'Navegue, filtre e baixe projetos de estudantes sem fazer login.',
        'project_types.webgl': 'Jogo WebGL',
        'project.webgl_section': 'Jogo WebGL',
        'project.webgl_play': 'Jogar no navegador',
        'project.webgl_open': 'Abrir em uma nova guia',
        'add_project.add_subtitle': 'Preencha os detalhes do seu projeto e publique o no portal.',
        'add_project.edit_subtitle': 'Atualize as informações do seu projeto.',
        'add_project.basic_section': 'Informações básicas',
        'add_project.media_section': 'Mídia',
        'add_project.required_note': 'Campos marcados com * são obrigatórios.',
        'add_project.webgl_source_label': 'Como exibir o jogo',
        'add_project.webgl_mode_build': 'Enviar build',
        'add_project.webgl_mode_url': 'URL externa',
        'add_project.webgl_build_label': 'Build WebGL (arquivo ZIP)',
        'add_project.webgl_build_btn': 'Escolher arquivo',
        'add_project.webgl_build_hint': 'Envie um arquivo ZIP com sua build WebGL. O arquivo deve incluir um arquivo index.html. Tamanho máx: 100 MB.',
        'add_project.webgl_url_label': 'URL do jogo WebGL',
        'add_project.webgl_url_hint': 'A URL onde o jogo está hospedado. Será incorporado no portal.',
        'add_project.missing_desc_title': 'Descrição muito curta',
        'add_project.missing_desc_desc': 'A descrição deve conter pelo menos 10 palavras.',
        'add_project.missing_splash_title': 'Miniatura do projeto ausente',
        'add_project.missing_splash_desc': 'Faça upload de um pôster/miniatura. Ele é exibido no cartão do projeto.'
    }
};

function setValue(obj, path, value) {
    const keys = path.split('.');
    for (let i = 0; i < keys.length - 1; i++) {
        if (!obj[keys[i]]) obj[keys[i]] = {};
        obj = obj[keys[i]];
    }
    obj[keys[keys.length - 1]] = value;
}

for (const [lang, map] of Object.entries(translations)) {
    const fp = path.join(locales_dir, lang + '.json');
    if (fs.existsSync(fp)) {
        const data = JSON.parse(fs.readFileSync(fp, 'utf-8'));
        for (const [k, v] of Object.entries(map)) {
            setValue(data, k, v);
        }
        fs.writeFileSync(fp, JSON.stringify(data, null, 2) + '\n', 'utf-8');
        console.log("Updated " + lang + ".json");
    } else {
        console.log("Skipped " + lang + ".json (not found)");
    }
}
